#!/bin/bash
# ==============================================================================
# Vibe Trading India — OCI ARM VM Setup Script
# ==============================================================================
# Target: Oracle Cloud Free Tier A1.Flex (4 OCPU, 24GB RAM, Ubuntu 22.04 ARM64)
# This script sets up the complete trading infrastructure.
# ==============================================================================

set -euo pipefail

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log() { echo -e "${GREEN}[$(date +%H:%M:%S)]${NC} $1"; }
warn() { echo -e "${YELLOW}[$(date +%H:%M:%S)] WARNING:${NC} $1"; }
err() { echo -e "${RED}[$(date +%H:%M:%S)] ERROR:${NC} $1"; }

# ── Pre-flight Checks ───────────────────────────────────────

log "═══ Vibe Trading India — OCI Setup ═══"
log "Architecture: $(uname -m)"
log "OS: $(lsb_release -ds 2>/dev/null || cat /etc/os-release | head -1)"
log "RAM: $(free -h | awk '/^Mem:/{print $2}')"

if [[ "$(uname -m)" != "aarch64" ]]; then
    warn "Not running on ARM64 — some steps may differ."
fi

# ── Step 1: System Dependencies ──────────────────────────────

log "Step 1/7: Installing system dependencies..."
sudo apt-get update -qq
sudo apt-get install -y -qq \
    python3.11 python3.11-venv python3.11-dev \
    python3-pip \
    git curl wget jq \
    build-essential \
    ca-certificates \
    gnupg lsb-release

# ── Step 2: Install Ollama (ARM64 supported) ─────────────────

log "Step 2/7: Installing Ollama..."
if ! command -v ollama &>/dev/null; then
    curl -fsSL https://ollama.com/install.sh | sh
    log "Ollama installed successfully"
else
    log "Ollama already installed: $(ollama --version)"
fi

# Start Ollama service
sudo systemctl enable ollama 2>/dev/null || true
sudo systemctl start ollama 2>/dev/null || ollama serve &>/dev/null &
sleep 3

# Pull primary model
log "Pulling Llama 3.1 8B (Q4_K_M, ~4.7GB)..."
ollama pull llama3.1:8b || warn "Model pull failed — will retry later"

# Pull coding-focused model for strategy generation
log "Pulling Qwen2.5-Coder 7B..."
ollama pull qwen2.5-coder:7b || warn "Qwen pull failed — optional"

# ── Step 3: Clone Repositories ───────────────────────────────

log "Step 3/7: Cloning repositories..."
WORK_DIR="${HOME}/vibe-trading"
mkdir -p "$WORK_DIR"
cd "$WORK_DIR"

if [ ! -d "core-engine" ]; then
    git clone https://github.com/HKUDS/Vibe-Trading.git core-engine
fi

if [ ! -d "india-trade-cli" ]; then
    git clone https://github.com/hopit-ai/india-trade-cli.git india-trade-cli
fi

if [ ! -d "kite-mcp" ]; then
    git clone https://github.com/zerodha/kite-mcp-server.git kite-mcp
fi

# ── Step 4: Python Virtual Environment ──────────────────────

log "Step 4/7: Setting up Python environment..."
python3.11 -m venv "${WORK_DIR}/venv"
source "${WORK_DIR}/venv/bin/activate"

# Upgrade pip
pip install --upgrade pip setuptools wheel

# Install india-trade-cli
log "Installing india-trade-cli..."
cd "${WORK_DIR}/india-trade-cli"
pip install -e "." --quiet 2>&1 | tail -5

# Install Vibe-Trading core engine
log "Installing Vibe-Trading core engine..."
cd "${WORK_DIR}/core-engine"
pip install -e "." --quiet 2>&1 | tail -5

# Install orchestrator dependencies
pip install httpx python-dotenv --quiet

# ── Step 5: Configuration ───────────────────────────────────

log "Step 5/7: Setting up configuration..."
cd "$WORK_DIR"

# Create .env if it doesn't exist
if [ ! -f ".env" ]; then
    cat > .env << 'ENVEOF'
# Generated by setup_oci.sh — Edit with your actual API keys
TRADING_MODE=PAPER
TOTAL_CAPITAL=1000000
DEFAULT_RISK_PCT=2
AI_PROVIDER=openai
OPENAI_BASE_URL=http://localhost:11434/v1
OPENAI_API_KEY=ollama
AI_MODEL=llama3.1:8b
LANGCHAIN_PROVIDER=ollama
LANGCHAIN_MODEL_NAME=llama3.1:8b
OLLAMA_BASE_URL=http://localhost:11434/v1
LANGCHAIN_TEMPERATURE=0.0
TIMEOUT_SECONDS=120
MAX_RETRIES=2
STOCK_UNIVERSE=NIFTY50
MAX_DAILY_ANALYSES=5
BACKTEST_LOOKBACK_DAYS=90
IMPROVEMENT_THRESHOLD=1.05
HEALTH_CHECK_INTERVAL=5
ENVEOF
    log ".env created — update with your broker API keys"
else
    log ".env already exists"
fi

# Create necessary directories
mkdir -p ~/.trading_platform/{logs,journal,strategies}

# ── Step 6: Systemd Service ─────────────────────────────────

log "Step 6/7: Creating systemd service..."
sudo tee /etc/systemd/system/vibe-trading.service > /dev/null << SVCEOF
[Unit]
Description=Vibe Trading India — Daily Orchestrator
After=network-online.target ollama.service
Wants=network-online.target

[Service]
Type=simple
User=${USER}
WorkingDirectory=${WORK_DIR}
Environment="PATH=${WORK_DIR}/venv/bin:/usr/local/bin:/usr/bin:/bin"
ExecStart=${WORK_DIR}/venv/bin/python -m orchestrator.daily_cycle --daemon
Restart=always
RestartSec=30
StandardOutput=append:${HOME}/.trading_platform/logs/orchestrator.log
StandardError=append:${HOME}/.trading_platform/logs/orchestrator_error.log

[Install]
WantedBy=multi-user.target
SVCEOF

sudo systemctl daemon-reload
log "Service created (not started yet — enable with: sudo systemctl enable --now vibe-trading)"

# ── Step 7: Cron Setup (alternative to systemd) ─────────────

log "Step 7/7: Setting up cron schedule..."
CRON_SCRIPT="${WORK_DIR}/run_phase.sh"
cat > "$CRON_SCRIPT" << 'CRONEOF'
#!/bin/bash
cd ~/vibe-trading
source venv/bin/activate
python -m orchestrator.daily_cycle --phase "$1" 2>&1 | tee -a ~/.trading_platform/logs/cron_$(date +%Y%m%d).log
CRONEOF
chmod +x "$CRON_SCRIPT"

# Install crontab (IST = UTC+5:30, so subtract 5:30 from IST times)
# 08:45 IST = 03:15 UTC
# 09:15 IST = 03:45 UTC
# 09:30 IST = 04:00 UTC
# 12:30 IST = 07:00 UTC
# 15:15 IST = 09:45 UTC
# 16:00 IST = 10:30 UTC
# 17:00 IST = 11:30 UTC
CRON_ENTRIES="
# Vibe Trading India — Daily Schedule (times in UTC, IST = UTC+5:30)
15 3 * * 1-5 ${CRON_SCRIPT} premarket      # 08:45 IST Mon-Fri
45 3 * * 1-5 ${CRON_SCRIPT} analysis        # 09:15 IST
0  4 * * 1-5 ${CRON_SCRIPT} execute         # 09:30 IST
0  7 * * 1-5 ${CRON_SCRIPT} midday          # 12:30 IST
45 9 * * 1-5 ${CRON_SCRIPT} eod             # 15:15 IST
30 10 * * 1-5 ${CRON_SCRIPT} auto_improve   # 16:00 IST
30 11 * * 1-5 ${CRON_SCRIPT} auto_heal      # 17:00 IST
"

# Only add if not already present
if ! crontab -l 2>/dev/null | grep -q "vibe-trading"; then
    (crontab -l 2>/dev/null; echo "$CRON_ENTRIES") | crontab -
    log "Cron jobs installed"
else
    log "Cron jobs already exist"
fi

# ── Summary ─────────────────────────────────────────────────

echo ""
log "═══ Setup Complete ═══"
echo -e "
${BLUE}Installed Components:${NC}
  ✅ Ollama with Llama 3.1 8B + Qwen2.5-Coder 7B
  ✅ Vibe-Trading core engine
  ✅ india-trade-cli (7-agent analysis)
  ✅ Kite MCP Server (repo cloned)
  ✅ Orchestrator with daily cycle
  ✅ Systemd service + cron schedule

${YELLOW}Next Steps:${NC}
  1. Edit ${WORK_DIR}/.env with your API keys:
     - KITE_API_KEY / KITE_API_SECRET (Zerodha)
     - OPENROUTER_API_KEY (optional fallback)
     - TELEGRAM_BOT_TOKEN (optional alerts)

  2. Test Ollama: ollama run llama3.1:8b 'What is NIFTY 50?'

  3. Test india-trade-cli: cd india-trade-cli && trade analyze RELIANCE

  4. Test orchestrator health: python -m orchestrator.daily_cycle --health

  5. Start daemon: sudo systemctl enable --now vibe-trading
     OR use cron (already installed, runs Mon-Fri)

${RED}⚠️  IMPORTANT:${NC}
  - TRADING_MODE is set to PAPER — NEVER change to LIVE without review
  - Register this VM's static IP on Zerodha console for API access
  - Paper trading does not require IP registration
"
