"""
market/symbols.py
─────────────────
Standard NSE symbol lists.
"""

NIFTY_50 = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK",
    "HINDUNILVR", "ITC", "SBIN", "BHARTIARTL", "KOTAKBANK",
    "LT", "AXISBANK", "BAJFINANCE", "ASIANPAINT", "MARUTI",
    "TITAN", "SUNPHARMA", "TATAMOTORS", "WIPRO", "ULTRACEMCO",
    "NTPC", "ONGC", "POWERGRID", "TATASTEEL", "INDUSINDBK",
    "JSWSTEEL", "ADANIENT", "ADANIPORTS", "BAJAJFINSV", "COALINDIA",
    "TECHM", "HCLTECH", "NESTLEIND", "DRREDDY", "CIPLA",
    "DIVISLAB", "GRASIM", "EICHERMOT", "APOLLOHOSP", "HEROMOTOCO",
    "BRITANNIA", "M&M", "TATACONSUM", "HINDALCO", "BPCL",
    "BAJAJ-AUTO", "SHRIRAMFIN", "SBILIFE", "HDFCLIFE", "LTIM",
]

BANK_NIFTY = [
    "HDFCBANK", "ICICIBANK", "KOTAKBANK", "AXISBANK", "SBIN",
    "INDUSINDBK", "AUBANK", "BANDHANBNK", "FEDERALBNK", "IDFCFIRSTB",
    "PNB", "BANKBARODA",
]
